### PR TITLE
Add Support for unity-2019.2.17-mbe and unity-2019.2.4-mbe

### PR DESCRIPTION
**Pull request by Kr4ken-9**
I apologize for not adding 2019.2.4 first, 2019.2.17 happened to download first for whatever reason. I followed the instructions and built mono-2.0-bdwgc.dll successfully with these changes. (I did not test if it works beyond that because to be honest I don't know how)

The timestamps for mono-2.0-bdwgc.dll were (same for both versions):
UTC  : 11/4/2019 2:50:35 PM
LOCAL: 11/4/2019 8:50:35 AM

I couldn't find a merge that was close to that time... Looking back the readme says mono.dll so I'm not sure if I was supposed to check for this timestamp anyway

The timestamps for mono.dll were (32 nondevelopment):
UTC  : 3/10/2019 1:52:30 PM
LOCAL: 3/10/2019 8:52:30 AM

(64 nondevelopment):
UTC  : 3/10/2019 1:53:57 PM
LOCAL: 3/10/2019 8:53:57 AM

I chose commit #67c73d284892c851e77bcd33e2db12c28a5d88d3 because it was the closest merge before the PE header timestamp. I have limited understanding but I took that to mean that mono.dll was built according to that timestamp. So, by my logic, the merge would have to have occurred before mono.dll was built. Otherwise, there was another merge a day after this mono.dll was built.

### CODE REVIEW

**Comment by Kr4ken-9** [comment]
Oh boy. I think I need to fix this and make a new pull request lol

**Comment by Kr4ken-9** [comment]
I also added support the files for unity-2019.2.4-mbe. The timestamps for the 2019.2.4-mbe files were:

mono.dll
32nondevelopment
UTC  : 3/10/2019 1:52:30 PM
LOCAL: 3/10/2019 8:52:30 AM

64nondevelopment
UTC  : 3/10/2019 1:53:57 PM
LOCAL: 3/10/2019 8:53:57 AM

mono-2.0-bdwgc.dll
64development
UTC  : 8/6/2019 12:30:21 PM
LOCAL: 8/6/2019 7:30:21 AM

64nondevelopment
UTC  : 8/6/2019 12:30:21 PM
LOCAL: 8/6/2019 7:30:21 AM

AKA matching the timestamps for the 2019.2.17-mbe files. Therefore, I used the same merge for the commit hash. Does this mean the versions between 2019.2.4-mbe and 2019.2.17-mbe are identical? It would save a lot of time if they were...

**Comment by Kr4ken-9** [comment]
One thing I noticed is that the hash for unity-2019.2.0-mbe
`f93c5973976e4bec5e769a31a73f00003f0a32dc`
is actually from May 31. Also, it is the latest merge on the unity-2019.2.0-mbe.

Now that I've realized this, I think I was actually supposed to use the timestamps for mono-2.0-bdwgc.dll. Which means, my commits right now are for the wrong merge commit hash. However, since May 31st is the latest merge on that branch, does that mean all (2019.2.0-mbe through 2019.2.21) 2019.2 use the same commit hash?

Since the timestamps on mono-2.0-bdwgc.dll are actually more recent than the latest merge, should I actually be looking for the closest commit, rather than the closest merge? I will hold off on updating any more until I figure that out.

**Comment by 0xd4d** [comment]
You should use the timestamps from mono.dll if it's the non-mbe (old) branch, and mono-2.0-bdwgc if it's the -mbe version.

> UTC : 8/6/2019 12:30:21 PM

Is this august or june?

**Comment by Kr4ken-9** [comment]
Based on a timestamp of a random dll:
```
UTC  : 12/18/2018 8:09:05 AM
LOCAL: 12/18/2018 2:09:05 AM
```
It is August based on M/D/Y

**Comment by 0xd4d** [comment]
I haven't verified the hash yet, will do that later.

Can you also open a PR for the master branch?

**Comment by Kr4ken-9** [comment]
I think I will have to close this PR and open a new one using correct hashes. I used the timestamps for the mono.dll by mistake and the unity-2019.2.0-mbe is actually built against a more recent mono commit than the unity-2019.2.4-mbe and unity-2019.2.17-mbe.

If you do take a look at the hashes, can you confirm for me that I would be using this commit (https://github.com/Unity-Technologies/mono/commit/f93c5973976e4bec5e769a31a73f00003f0a32dc) to build all of the unity-2019.2.x-mbe monos? I would assume so because it is the latest merge in the unity-2019.2-mbe branch. However, I am just unsure since it would mean all of the unity-2019.2 (even the one already built by you) would be using the same commit hash, which doesn't appear to be normal looking at the hash list.

**Comment by 0xd4d** [comment]
branch: unity-2019.2-mbe

hash: d1502a3c09e3b69463a19ea6e03b08d82e1fbbce

```
Author: UnityAlex <alexthibodeau@unity3d.com>  2019-07-31 19:33:45
Committer: UnityAlex <alexthibodeau@unity3d.com>  2019-08-06 14:16:23
```

That one has the correct commit date.

**Comment by Kr4ken-9** [comment]
So I am not necessarily looking for a merge commit but just any commit with the correct timestamp?

**Comment by 0xd4d** [comment]
I saw no merges, and I picked the one with the same date as the binary.

git log --graph --oneline -40

**Pull request closed without merging**
