### PR TITLE
2018.4.15-mbe

### PR DESCRIPTION
**Pull request by MikalMirkas**
Tested with One Step From Eden and dnSpy's Unity connect feature, after converting the game from a release build to debug mode.

### CODE REVIEW

**Comment by 0xd4d** [comment]
Could you add `2018.4.15` too (the non-mbe version)?

You should also add a PR against the master branch.

> Tested with One Step From Eden and dnSpy's Unity connect feature, after converting the game from a release build to debug mode.

The debug builds don't need a patched dll file since they have debugging enabled. You should test release builds.

**Comment by MikalMirkas** [comment]
> The debug builds don't need a patched dll file since they have debugging enabled. You should test release builds.

Oh. I was under the impression that it required it. That would have saved me some work.

The current release build crashes when I try to open it through dnSpy. However, it immediately reboots, breaking any ability to hook into it with a debugger without using the Unity (Connect) tool. It **does work** when I connect into it, and I can use breakpoints. I probably grabbed the wrong commit or something.

>You should also add a PR against the master branch.

Ok. I assume I have to run the scripts again but on the master branch?

>Could you add `2018.4.15` too (the non-mbe version)?

Sure.

**Comment by 0xd4d** [comment]
Your commit hashes appear to be wrong

commit | unity | date
--------|-----|-------
a25e18c6b7f9229cfe61aaefd0d4fc205f43a761 | unity-2018.4.15 | 2019-03-10
77a1ed72a23271012ab9c2f7fdfa0b4b6996ddf9 | unity-2018.4.15-mbe | 2019-03-11

This is what I got.

commit | unity | date
--------|-----|-------
fe1fb53ecc6e26f9c19a7018d4ac19f22c25e964 | unity-2018.4.15 | 2019-06-18
fc58448f0d127d58604135f1ed06b7c91d0b5b21 | unity-2018.4.15-mbe | 2019-11-01

You can see the commit date like so: `git log -1 --format=fuller fc58448f0d127d58604135f1ed06b7c91d0b5b21`

Did you run the umpatcher to get the timstamps of the files? `mono.dll` has timestamp 2019-06-18 and `mono-2.0-bdwgc.dll` has timestamp 2019-11-01.

**Comment by 0xd4d** [comment]
Thanks for the PR, but I've used the hashes I found and pushed them to the repo so I'll close this.

**Comment by MikalMirkas** [comment]
I did run umpatcher, but I wasn't sure whether the dates needed to line up for both. I may have malformatted my date string when feeding into gitk though as I didn't want to filter through hundreds of commits. I used the most recent merge as of the normal unity date, which was (allegedly) in March.

Edit 2: I wasn't sure if MBE and Mono were generated synchronously, so I just used my gut and went with the more recent version.

Edit 3: Actually, I am incorrect. I went through my logs and saw that I originally did use the fc5844 hash for mbe, but I did something wrong and it refused to connect. I started trying earlier and earlier ones until I gave up and went back to the earliest confirmed hashes and then redid the entire patching process. I didn't do extensive enough testing before trying to repatch. That's why I used the outdated hashes for mbe, and assumed that the mono one would correlate as well.

Thanks for cleaning it up. Cheers.

**Pull request closed without merging**
